name: Build and Upload

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.png"
      - "**.jpg"
      - "**.jpeg"
      - ".gitignore"
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        qt-version: [ 6.5.1]
        library-type: [ shared, static]
        platform: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - platform: windows-latest
            CC: cl
            CXX: cl
            LD: link
            EXTRA_FLAGS: -DFRAMELESSHELPER_ENABLE_SPECTRE=ON -DFRAMELESSHELPER_ENABLE_EHCONTGUARD=ON -DFRAMELESSHELPER_ENABLE_INTELCET=ON -DFRAMELESSHELPER_ENABLE_CFGUARD=ON
          - platform: ubuntu-latest
            CC: gcc
            CXX: g++
            LD: ld
            EXTRA_FLAGS: -DFRAMELESSHELPER_ENABLE_SPECTRE=ON -DFRAMELESSHELPER_ENABLE_INTELCET=ON -DFRAMELESSHELPER_ENABLE_CFGUARD=ON
          - platform: macos-latest
            CC: /usr/local/opt/llvm/bin/clang
            CXX: /usr/local/opt/llvm/bin/clang++
            LD: /usr/local/opt/llvm/bin/ld64.lld
            EXTRA_FLAGS: -DFRAMELESSHELPER_ENABLE_UNIVERSAL_BUILD=OFF
          - library-type: shared
            lib_type_flag: -DFRAMELESSHELPER_BUILD_STATIC=OFF
          - library-type: static
            lib_type_flag: -DFRAMELESSHELPER_BUILD_STATIC=ON

    runs-on: ${{ matrix.platform }}
    continue-on-error: true
    
    steps:
    - name: Macos/Linux Setup rsync
      if: ${{ matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest' }}
      uses: GuillaumeFalourd/setup-rsync@v1.1
    - name: Macos/Linux Test rsync 
      if: ${{ matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest' }}
      run: rsync --version
      
    - name: Windows Enable WSL
      if: ${{ matrix.platform == 'windows-latest'}}
      run: dism.exe /online /disable-feature /featurename:Microsoft-Windows-Subsystem-Linux /norestart  && ^
          dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart


    - name: Windows Install Ubuntu
      if: ${{ matrix.platform == 'windows-latest'}}
      run: wsl --set-default-version 2 && wsl --install -d Ubuntu
      shell: powershell

    - name: Windows Update and Install rsync
      if: ${{ matrix.platform == 'windows-latest'}}
      run: |
        wsl sudo apt-get update
        wsl sudo apt-get install -y rsync

    - name: Windows Run rsync
      if: ${{ matrix.platform == 'windows-latest'}}
      run: |
        wsl rsync --version
